{{- if .Values.persistent.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-nginx-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: {{ .Values.persistent.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistent.size }}
{{- end }}
